name: Cache Demo

on:
 push:

jobs:
 cache-job:
  runs-on: ubuntu-latest

  steps:
    - name: prime-cache-28e6edb
      uses: actions/checkout@v4

    - name: cache-28e6edb
      id: cache_step
      uses: actions/cache@v4
      with:
        path: ~/.cache
        key: cache-28e6edb

    - name: Show cache result
      run: |
           echo "Cache result: ${{ steps.cache_step.outputs.cache-hit }}"
